// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/prismaapi/adsmanager/commonads': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/adsmanager/commonads.post').default>>>>
    }
    '/api/prismaapi/author/getauthorpost': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/author/getauthorpost.post').default>>>>
    }
    '/api/prismaapi/breakingnews/breaking': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/breakingnews/breaking.get').default>>>>
    }
    '/api/prismaapi/category/categorycontent': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/category/categorycontent.post').default>>>>
    }
    '/api/prismaapi/collection/latestpost': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/collection/latestpost.post').default>>>>
    }
    '/api/prismaapi/detail/alllatestpost': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/detail/alllatestpost.get').default>>>>
    }
    '/api/prismaapi/detail/firstrightcatcontent': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/detail/firstrightcatcontent.post').default>>>>
    }
    '/api/prismaapi/detail/getinsidemorenews': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/detail/getinsidemorenews.post').default>>>>
    }
    '/api/prismaapi/detail/moredetailcontents': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/detail/moredetailcontents.post').default>>>>
    }
    '/api/prismaapi/detail/moreinsidemorenews': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/detail/moreinsidemorenews.post').default>>>>
    }
    '/api/prismaapi/detail/mreletedcontents': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/detail/mreletedcontents.post').default>>>>
    }
    '/api/prismaapi/detail/postdetail': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/detail/postdetail.post').default>>>>
    }
    '/api/prismaapi/gallery/albumcategoryphotos': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/gallery/albumcategoryphotos.post').default>>>>
    }
    '/api/prismaapi/gallery/albumdetail': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/gallery/albumdetail.post').default>>>>
    }
    '/api/prismaapi/header/allcategory': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/header/allcategory.get').default>>>>
    }
    '/api/prismaapi/header/banglatime': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/header/banglatime.get').default>>>>
    }
    '/api/prismaapi/header/headercategory': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/header/headercategory.get').default>>>>
    }
    '/api/prismaapi/home/art': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/art.get').default>>>>
    }
    '/api/prismaapi/home/campus': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/campus.get').default>>>>
    }
    '/api/prismaapi/home/career': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/career.get').default>>>>
    }
    '/api/prismaapi/home/categorycontent': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/categorycontent.post').default>>>>
    }
    '/api/prismaapi/home/child': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/child.get').default>>>>
    }
    '/api/prismaapi/home/corporate': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/corporate.get').default>>>>
    }
    '/api/prismaapi/home/counter': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/counter.get').default>>>>
    }
    '/api/prismaapi/home/crime': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/crime.get').default>>>>
    }
    '/api/prismaapi/home/economy': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/economy.get').default>>>>
    }
    '/api/prismaapi/home/education': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/education.get').default>>>>
    }
    '/api/prismaapi/home/entertainment': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/entertainment.get').default>>>>
    }
    '/api/prismaapi/home/galleryphoto': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/galleryphoto.get').default>>>>
    }
    '/api/prismaapi/home/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/health.get').default>>>>
    }
    '/api/prismaapi/home/international': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/international.get').default>>>>
    }
    '/api/prismaapi/home/lawcourt': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/lawcourt.get').default>>>>
    }
    '/api/prismaapi/home/lifestyle': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/lifestyle.get').default>>>>
    }
    '/api/prismaapi/home/literature': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/literature.get').default>>>>
    }
    '/api/prismaapi/home/motivation': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/motivation.get').default>>>>
    }
    '/api/prismaapi/home/national': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/national.get').default>>>>
    }
    '/api/prismaapi/home/opinion': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/opinion.get').default>>>>
    }
    '/api/prismaapi/home/politics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/politics.get').default>>>>
    }
    '/api/prismaapi/home/positioncontent': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/positioncontent.post').default>>>>
    }
    '/api/prismaapi/home/probash': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/probash.get').default>>>>
    }
    '/api/prismaapi/home/religion': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/religion.get').default>>>>
    }
    '/api/prismaapi/home/saradesh': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/saradesh.get').default>>>>
    }
    '/api/prismaapi/home/specialarticle': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/specialarticle.get').default>>>>
    }
    '/api/prismaapi/home/specialreport': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/specialreport.get').default>>>>
    }
    '/api/prismaapi/home/specialtopcontent': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/specialtopcontent.get').default>>>>
    }
    '/api/prismaapi/home/sports': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/sports.get').default>>>>
    }
    '/api/prismaapi/home/technology': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/technology.get').default>>>>
    }
    '/api/prismaapi/home/videofeature': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/home/videofeature.post').default>>>>
    }
    '/api/prismaapi/ogimage/ogimage': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/ogimage/ogimage.post').default>>>>
    }
    '/api/prismaapi/search/search': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/search/search.post').default>>>>
    }
    '/api/prismaapi/sitesetting/sitesetting': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/sitesetting/sitesetting.get').default>>>>
    }
    '/api/prismaapi/subcategory/subcategorycontent': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/subcategory/subcategorycontent.post').default>>>>
    }
    '/api/prismaapi/tabs/latestpost': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/tabs/latestpost.post').default>>>>
    }
    '/api/prismaapi/tabs/popularpost': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/tabs/popularpost.post').default>>>>
    }
    '/api/prismaapi/tag/tagcontents': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/tag/tagcontents.post').default>>>>
    }
    '/api/prismaapi/video/allvideo': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/video/allvideo.get').default>>>>
    }
    '/api/prismaapi/video/categoryvideos': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/video/categoryvideos.post').default>>>>
    }
    '/api/prismaapi/video/singlevideo': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/prismaapi/video/singlevideo.post').default>>>>
    }
    '/api/v1/adsmanager/commonads': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/adsmanager/commonads.post').default>>>>
    }
    '/api/v1/author/getauthorpost': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/author/getauthorpost.post').default>>>>
    }
    '/api/v1/breakingnews/breaking': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/breakingnews/breaking.get').default>>>>
    }
    '/api/v1/category/categorycontent': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/category/categorycontent.post').default>>>>
    }
    '/api/v1/collection/latestpost': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/collection/latestpost.post').default>>>>
    }
    '/api/v1/detail/alllatestpost': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/detail/alllatestpost.get').default>>>>
    }
    '/api/v1/detail/firstrightcatcontent': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/detail/firstrightcatcontent.post').default>>>>
    }
    '/api/v1/detail/getinsidemorenews': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/detail/getinsidemorenews.post').default>>>>
    }
    '/api/v1/detail/moredetailcontents': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/detail/moredetailcontents.post').default>>>>
    }
    '/api/v1/detail/moreinsidemorenews': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/detail/moreinsidemorenews.post').default>>>>
    }
    '/api/v1/detail/mreletedcontents': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/detail/mreletedcontents.post').default>>>>
    }
    '/api/v1/detail/postdetail': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/detail/postdetail.post').default>>>>
    }
    '/api/v1/gallery/albumcategoryphotos': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/gallery/albumcategoryphotos.post').default>>>>
    }
    '/api/v1/gallery/albumdetail': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/gallery/albumdetail.post').default>>>>
    }
    '/api/v1/header/allcategory': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/header/allcategory.get').default>>>>
    }
    '/api/v1/header/banglatime': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/header/banglatime.get').default>>>>
    }
    '/api/v1/header/headercategory': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/header/headercategory.get').default>>>>
    }
    '/api/v1/home/art': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/art.get').default>>>>
    }
    '/api/v1/home/campus': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/campus.get').default>>>>
    }
    '/api/v1/home/career': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/career.get').default>>>>
    }
    '/api/v1/home/categorycontent': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/categorycontent.post').default>>>>
    }
    '/api/v1/home/child': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/child.get').default>>>>
    }
    '/api/v1/home/corporate': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/corporate.get').default>>>>
    }
    '/api/v1/home/counter': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/counter.get').default>>>>
    }
    '/api/v1/home/crime': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/crime.get').default>>>>
    }
    '/api/v1/home/economy': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/economy.get').default>>>>
    }
    '/api/v1/home/education': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/education.get').default>>>>
    }
    '/api/v1/home/entertainment': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/entertainment.get').default>>>>
    }
    '/api/v1/home/galleryphoto': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/galleryphoto.get').default>>>>
    }
    '/api/v1/home/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/health.get').default>>>>
    }
    '/api/v1/home/international': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/international.get').default>>>>
    }
    '/api/v1/home/lawcourt': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/lawcourt.get').default>>>>
    }
    '/api/v1/home/lifestyle': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/lifestyle.get').default>>>>
    }
    '/api/v1/home/literature': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/literature.get').default>>>>
    }
    '/api/v1/home/motivation': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/motivation.get').default>>>>
    }
    '/api/v1/home/national': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/national.get').default>>>>
    }
    '/api/v1/home/opinion': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/opinion.get').default>>>>
    }
    '/api/v1/home/politics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/politics.get').default>>>>
    }
    '/api/v1/home/positioncontent': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/positioncontent.post').default>>>>
    }
    '/api/v1/home/probash': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/probash.get').default>>>>
    }
    '/api/v1/home/religion': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/religion.get').default>>>>
    }
    '/api/v1/home/saradesh': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/saradesh.get').default>>>>
    }
    '/api/v1/home/specialarticle': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/specialarticle.get').default>>>>
    }
    '/api/v1/home/specialreport': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/specialreport.get').default>>>>
    }
    '/api/v1/home/specialtopcontent': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/specialtopcontent.get').default>>>>
    }
    '/api/v1/home/sports': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/sports.get').default>>>>
    }
    '/api/v1/home/technology': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/technology.get').default>>>>
    }
    '/api/v1/home/videofeature': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/home/videofeature.post').default>>>>
    }
    '/api/v1/ogimage/ogimage': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/ogimage/ogimage.post').default>>>>
    }
    '/api/v1/search/search': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/search/search.post').default>>>>
    }
    '/api/v1/sitesetting/sitesetting': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/sitesetting/sitesetting.get').default>>>>
    }
    '/api/v1/subcategory/subcategorycontent': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/subcategory/subcategorycontent.post').default>>>>
    }
    '/api/v1/tabs/latestpost': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/tabs/latestpost.post').default>>>>
    }
    '/api/v1/tabs/popularpost': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/tabs/popularpost.post').default>>>>
    }
    '/api/v1/tag/tagcontents': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/tag/tagcontents.post').default>>>>
    }
    '/api/v1/video/allvideo': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/video/allvideo.get').default>>>>
    }
    '/api/v1/video/categoryvideos': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/video/categoryvideos.post').default>>>>
    }
    '/api/v1/video/latestvideo': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/video/latestvideo.post').default>>>>
    }
    '/api/v1/video/latestvideos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/video/latestvideos.get').default>>>>
    }
    '/api/v1/video/singlevideo': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/video/singlevideo.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}